### PR TITLE
Ruby24

### PR DESCRIPTION
**Pull request by jreidinger**
workaround for issue in ruby 2.4. For details see https://bugzilla.novell.com/show_bug.cgi?id=1048526

### CODE REVIEW

**Comment by mvidner** [comment]
OK, but what is the context? Where is the failing build/test? Do we have a tracking bsc# already?

**Comment by jreidinger** [comment]
@mvidner read emails :) 

PBI is https://trello.com/c/7YTu57vr/1075-5-sle15-tw-ruby-24-support
email is on yast-internal and there are also failures.
No bsc for it, but I use it as part of SLE15 adaptation

And also this is no merge commit yet, as you can see from content. It is just something I want to demonstrate to @lslezak

**Comment by mvidner** [comment]
Thanks!
For reference, the (internal) email is https://mailman.suse.de/mlarch//SuSE/yast-internal/2017/yast-internal.2017.07/msg00120.html
The build failure: https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:K/yast2-registration/standard/x86_64
```
[   31s]   30) Registration::UI::RegistrationUpdateDialog.run updates system registration, base and add-on products
[   31s]       Failure/Error: [true, load_yaml_fixture("remote_product.yml")]
[   31s] 
[   31s]       ArgumentError:
[   31s]         wrong number of arguments (given 0, expected 1)
[   31s]       # ./test/spec_helper.rb:35:in `load_yaml_fixture'
[   31s]       # ./test/registration_update_dialog_test.rb:21:in `block (3 levels) in <top (required)>'
```
which is in more detail (BT by Pepa)
```
[    3s] #<ArgumentError: wrong number of arguments (given 0, expected 1)>
[    3s] /usr/lib64/ruby/gems/2.4.0/gems/suse-connect-0.3.2/lib/suse/connect/remote/product.rb:12:in `initialize'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/to_ruby.rb:373:in `new'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/to_ruby.rb:373:in `revive'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/visitor.rb:16:in `visit'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/visitor.rb:6:in `accept'
[    3s] /usr/lib64/ruby/2.4.0/psych/visitors/to_ruby.rb:32:in `accept'
[    3s] /usr/lib64/ruby/2.4.0/psych/nodes/node.rb:38:in `to_ruby'
[    3s] /usr/lib64/ruby/2.4.0/psych.rb:253:in `load'
[    3s] /usr/lib64/ruby/2.4.0/psych.rb:473:in `block in load_file'
[    3s] /usr/lib64/ruby/2.4.0/psych.rb:472:in `open'
[    3s] /usr/lib64/ruby/2.4.0/psych.rb:472:in `load_file'
[    3s] /home/abuild/rpmbuild/BUILD/yast2-registration-3.2.12/test/spec_helper.rb:39:in `load_yaml_fixture'
[    3s] /home/abuild/rpmbuild/BUILD/yast2-registration-3.2.12/test/registration_update_dialog_test.rb:21:in `block (3 levels) in <top (required)>'
```

**Comment by mvidner** [comment]
BTW it also fails with a much shorter fixture, https://github.com/yast/yast-registration/blob/master/test/fixtures/installed_sles12_product.yml

**Comment by mvidner** [comment]
As the problematic class is a descendant of `OpenStruct`, it seems the corresponding upstream problem is https://github.com/ruby/psych/issues/263

**Comment by mvidner** [comment]
The reason that https://github.com/SUSE/connect alone does not trigger this problem is that it uses JSON, not YAML, for its test fixtures.

**Pull request merged**
