### PR TITLE
Enable [Next] button in the first boot workflow (bsc#970572)

### PR DESCRIPTION
**Pull request by lslezak**
... to allow using the registration module.

Pass the WFM arguments with the Back/Next status to the internally
called client.

The dialog correctly uses `Yast::GetInstArgs.enable_next` but the arguments were not passed
in the `scc` wrapper and the `GetInstArgs` used the `false` default values.

See bug https://bugzilla.suse.com/show_bug.cgi?id=970572

- 3.1.166.1

## Original State

The *Back* and *Next* button were disabled, the workflow got stuck:

firstboot_registration_broken

## With the Fix

The buttons are enabled and you can proceed:

firstboot_registration_fixed

### CODE REVIEW

**Comment by kobliha** [comment]
Something seems to be wrong

```
Failed to reach a server:
 [Errno 113] No route to host: 'https://api.suse.de/source/Devel:YaST:SLE-12-SP1/yast2-registration/_meta'
```

**Comment by mvidner** [comment]
> No route to host: 'https://api.suse.de/

Well yes, the openSUSE Jenkins will not be able to see the internal repos. But aren't they available externally too?

**Comment by lslezak** [comment]
That problem was caused by obsolete `yast-rake` at Jenkins. Updated, now we are blocked by the (already fixed) bnc check. (https://ci.opensuse.org/job/yast-registration-github-push/503/console)

**Comment by mvidner** [comment]
LGTM.

**Comment by lslezak** [comment]
Customer reported success with this patch, merging and submitting to maintenance...

**Pull request merged**
