### PR TITLE
Set the correct vendor change flag (FATE#319128)

### PR DESCRIPTION
**Pull request by lslezak**
for the DUP mode instead of the normal mode

- 3.1.137

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM, but how it behave if it is not defined for older versions?

**Comment by lslezak** [comment]
The `yast2-pkg-bindings` dependency has been updated, it cannot be undefined.

**Comment by jreidinger** [comment]
I mean your new condition in code

**Comment by lslezak** [comment]
The target is SLE12-SP1 and SLE12-GA backport, other older versions from YaST:Head do not make sense for registration anyway.

**Pull request merged**
