### PR TITLE
Theme fixes

### PR DESCRIPTION
**Pull request by jreidinger**
Draft of layout changes in registration dialog in installation. Several possible changes are shown. Basically each option represent evolution done by each commit.

## Vertical Spacing Only
The first commit is just remove of vertical spacing:
qt:
reg_qt
ncurses:
reg_ncurses

## Left Align
The second try to remove center align and instead align to left:
qt:
reg_qt_left

ncurses:
reg_ncurses_left

and minimal ncurses
reg_ncurses_left_min

## Left Align and Margin Box
The third try includes left align and margin box around
reg_qt_left_margin
reg_ncurses_left_margin

## Left Align and Horizontal Stretch
The forth try uses HStretch instead of Margin Box.
reg_qt_left_stretch
reg_ncurses_left_stretch
reg_qt_left_min_stretch

## Left Align and Horizontal Stretch and Network Button separate
It is same as previous one, just network button is moved to right edge. Looks like there is agreement that this layout is the best one from proposed.
reg_qt_left_stretch_nb
reg_ncurses_left_stretch_nb
reg_ncurses_left_stretch_min_nb

### CODE REVIEW

**Comment by jreidinger** [comment]
@kwwii Can you check screenshots here what you prefer? On the second set I can also try to define instead min size for input fields and remove it horizontal stretching, so it can be shorter in qt and also ncurses.

**Comment by jreidinger** [comment]
One more screenshot for default center aligned registration with high resolution which result in different view ( just part attached )

reg_qt_high_res

**Comment by mvidner** [comment]
For testing of big-resolution layouts it may be helpful to scale down the qemu display so that it still fits your physical screen:

man qemu-kvm:

```
       During the graphical emulation, you can use special key combinations to
       change modes. The default key mappings are shown below, but if you use
       "-alt-grab" then the modifier is Ctrl-Alt-Shift (instead of Ctrl-Alt)
       and if you use "-ctrl-grab" then the modifier is the right Ctrl key
       (instead of Ctrl-Alt):

       Ctrl-Alt-f
           Toggle full screen

       Ctrl-Alt-+
           Enlarge the screen

       Ctrl-Alt--
           Shrink the screen

       Ctrl-Alt-u
           Restore the screen's un-scaled dimensions
```

**Comment by lslezak** [comment]
After some discussion we decided to close it, this is just a low priority UI improvement...

**Pull request closed without merging**
